### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by TibiToz** [philhartung/aes67-sender#5]
Hey,

When starting the virtual sound card, i get this error:

$ node aes67 -a alsa -d 7 -n "Focusrite Scarlett 2i2"
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES 0.0.0.0:319
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at state.handle.lookup (dgram.js:243:14)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Toshiba01** [comment]
I'm getting the same error on a Macbook Pro OSX 10.13, Node V12

**Comment by Toshiba01** [comment]
> Hey,
> 
> When starting the virtual sound card, i get this error:
> 
> $ node aes67 -a alsa -d 7 -n "Focusrite Scarlett 2i2" events.js:174 throw er; // Unhandled 'error' event ^
> 
> Error: bind EACCES 0.0.0.0:319 at state.handle.lookup (dgram.js:242:18) at process._tickCallback (internal/process/next_tick.js:63:19) at Function.Module.runMain (internal/modules/cjs/loader.js:834:11) at startup (internal/bootstrap/node.js:283:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3) Emitted 'error' event at: at state.handle.lookup (dgram.js:243:14) at process._tickCallback (internal/process/next_tick.js:63:19) [... lines matching original stack trace ...] at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

I just found out, that you need to run it with root ( sudo ) and it works.
